module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.8-stable-14.09
cabal-file: project.cabal
version: 1
extra-packages: ! 'Hackage: data-memocombinators 0.3'
ghc-args: []
excluded-modules:
- euler20.hs
